:-module(grid_navigation_controller, [t/4]).

opposite_actions(step_up-q0,step_down-q2).
opposite_actions(step_down-q2,step_up-q0).
opposite_actions(step_left-q3,step_right-q1).
opposite_actions(step_right-q1,step_left-q3).

opposite_actions(step_up_right-q01,step_down_left-q23).
opposite_actions(step_down_right-q12,step_up_left-q30).
opposite_actions(step_down_left-q23,step_up_right-q01).
opposite_actions(step_up_left-q30,step_down_right-q12).

t(q0,pppu,step_up,q0).
t(q0,pppp,step_up_right,q01).
t(q0,pppu,step_up_right,q01).
t(q0,ppup,step_up_right,q01).
t(q0,ppuu,step_up_right,q01).
t(q0,pupp,step_up_right,q01).
t(q0,pupu,step_up_right,q01).
t(q0,puup,step_up_right,q01).
t(q0,puuu,step_up_right,q01).
t(q0,uppp,step_up_right,q01).
t(q1,pppp,step_up,q0).
t(q1,pppu,step_up,q0).
t(q1,ppup,step_up,q0).
t(q0,uppu,step_up_right,q01).
t(q1,ppuu,step_up,q0).
t(q1,pupp,step_up,q0).
t(q1,pupu,step_up,q0).
t(q0,ppup,step_up,q0).
t(q1,puup,step_up,q0).
t(q1,puuu,step_up,q0).
t(q0,upup,step_up_right,q01).
t(q1,pppp,step_up_right,q01).
t(q1,pppu,step_up_right,q01).
t(q1,ppup,step_up_right,q01).
t(q1,ppuu,step_up_right,q01).
t(q1,pupp,step_up_right,q01).
t(q1,pupu,step_up_right,q01).
t(q0,upuu,step_up_right,q01).
t(q1,puup,step_up_right,q01).
t(q1,puuu,step_up_right,q01).
t(q1,uppp,step_up_right,q01).
t(q1,uppu,step_up_right,q01).
t(q1,upup,step_up_right,q01).
t(q1,upuu,step_up_right,q01).
t(q1,uupp,step_up_right,q01).
t(q1,uupu,step_up_right,q01).
t(q1,uuup,step_up_right,q01).
t(q1,uuuu,step_up_right,q01).
t(q1,pppp,step_right,q1).
t(q0,uupp,step_up_right,q01).
t(q1,pppu,step_right,q1).
t(q1,ppup,step_right,q1).
t(q1,ppuu,step_right,q1).
t(q1,uppp,step_right,q1).
t(q1,uppu,step_right,q1).
t(q1,upup,step_right,q1).
t(q0,uupu,step_up_right,q01).
t(q1,upuu,step_right,q1).
t(q1,pppp,step_down_right,q12).
t(q1,pppu,step_down_right,q12).
t(q1,pupp,step_down_right,q12).
t(q0,uuup,step_up_right,q01).
t(q1,pupu,step_down_right,q12).
t(q1,uppp,step_down_right,q12).
t(q1,uppu,step_down_right,q12).
t(q1,uupp,step_down_right,q12).
t(q1,uupu,step_down_right,q12).
t(q0,uuuu,step_up_right,q01).
t(q1,pppp,step_down,q2).
t(q1,pppu,step_down,q2).
t(q1,pupp,step_down,q2).
t(q0,pppp,step_right,q1).
t(q1,pupu,step_down,q2).
t(q1,uppp,step_down,q2).
t(q1,uppu,step_down,q2).
t(q1,uupp,step_down,q2).
t(q1,uupu,step_down,q2).
t(q0,pppu,step_right,q1).
t(q1,pppp,step_down_left,q23).
t(q1,pppu,step_down_left,q23).
t(q1,ppup,step_down_left,q23).
t(q1,ppuu,step_down_left,q23).
t(q1,pupp,step_down_left,q23).
t(q1,pupu,step_down_left,q23).
t(q1,puup,step_down_left,q23).
t(q1,puuu,step_down_left,q23).
t(q1,uppp,step_down_left,q23).
t(q0,ppup,step_right,q1).
t(q1,uppu,step_down_left,q23).
t(q1,upup,step_down_left,q23).
t(q1,upuu,step_down_left,q23).
t(q1,uupp,step_down_left,q23).
t(q1,uupu,step_down_left,q23).
t(q1,uuup,step_down_left,q23).
t(q1,uuuu,step_down_left,q23).
t(q1,pppp,step_left,q3).
t(q1,ppup,step_left,q3).
t(q0,ppuu,step_right,q1).
t(q1,pupp,step_left,q3).
t(q1,puup,step_left,q3).
t(q1,uppp,step_left,q3).
t(q1,upup,step_left,q3).
t(q0,ppuu,step_up,q0).
t(q1,uupp,step_left,q3).
t(q1,uuup,step_left,q3).
t(q1,pppp,step_up_left,q30).
t(q1,pppu,step_up_left,q30).
t(q1,ppup,step_up_left,q30).
t(q1,ppuu,step_up_left,q30).
t(q1,pupp,step_up_left,q30).
t(q1,pupu,step_up_left,q30).
t(q1,puup,step_up_left,q30).
t(q1,puuu,step_up_left,q30).
t(q0,uppp,step_right,q1).
t(q0,uppu,step_right,q1).
t(q0,upup,step_right,q1).
t(q0,upuu,step_right,q1).
t(q0,pupp,step_up,q0).
t(q0,pppp,step_down_right,q12).
t(q0,pppu,step_down_right,q12).
t(q2,pppp,step_up,q0).
t(q2,pppu,step_up,q0).
t(q2,ppup,step_up,q0).
t(q2,ppuu,step_up,q0).
t(q2,pupp,step_up,q0).
t(q2,pupu,step_up,q0).
t(q2,puup,step_up,q0).
t(q2,puuu,step_up,q0).
t(q0,pupp,step_down_right,q12).
t(q2,pppp,step_up_right,q01).
t(q2,pppu,step_up_right,q01).
t(q2,ppup,step_up_right,q01).
t(q2,ppuu,step_up_right,q01).
t(q0,pupu,step_down_right,q12).
t(q2,pupp,step_up_right,q01).
t(q2,pupu,step_up_right,q01).
t(q2,puup,step_up_right,q01).
t(q2,puuu,step_up_right,q01).
t(q2,uppp,step_up_right,q01).
t(q2,uppu,step_up_right,q01).
t(q2,upup,step_up_right,q01).
t(q2,upuu,step_up_right,q01).
t(q2,uupp,step_up_right,q01).
t(q2,uupu,step_up_right,q01).
t(q2,uuup,step_up_right,q01).
t(q2,uuuu,step_up_right,q01).
t(q2,pppp,step_right,q1).
t(q2,pppu,step_right,q1).
t(q2,ppup,step_right,q1).
t(q2,ppuu,step_right,q1).
t(q2,uppp,step_right,q1).
t(q2,uppu,step_right,q1).
t(q2,upup,step_right,q1).
t(q2,upuu,step_right,q1).
t(q2,pppp,step_down_right,q12).
t(q2,pppu,step_down_right,q12).
t(q0,pupu,step_up,q0).
t(q0,uppp,step_down_right,q12).
t(q2,pupp,step_down_right,q12).
t(q2,pupu,step_down_right,q12).
t(q2,uppp,step_down_right,q12).
t(q2,uppu,step_down_right,q12).
t(q2,uupp,step_down_right,q12).
t(q0,uppu,step_down_right,q12).
t(q2,uupu,step_down_right,q12).
t(q2,pppp,step_down,q2).
t(q2,pppu,step_down,q2).
t(q2,pupp,step_down,q2).
t(q2,pupu,step_down,q2).
t(q2,uppp,step_down,q2).
t(q2,uppu,step_down,q2).
t(q2,uupp,step_down,q2).
t(q2,uupu,step_down,q2).
t(q2,pppp,step_down_left,q23).
t(q2,pppu,step_down_left,q23).
t(q2,ppup,step_down_left,q23).
t(q2,ppuu,step_down_left,q23).
t(q2,pupp,step_down_left,q23).
t(q2,pupu,step_down_left,q23).
t(q2,puup,step_down_left,q23).
t(q2,puuu,step_down_left,q23).
t(q2,uppp,step_down_left,q23).
t(q2,uppu,step_down_left,q23).
t(q2,upup,step_down_left,q23).
t(q0,uupp,step_down_right,q12).
t(q2,upuu,step_down_left,q23).
t(q2,uupp,step_down_left,q23).
t(q2,uupu,step_down_left,q23).
t(q2,uuup,step_down_left,q23).
t(q2,uuuu,step_down_left,q23).
t(q2,pppp,step_left,q3).
t(q2,ppup,step_left,q3).
t(q2,pupp,step_left,q3).
t(q0,uupu,step_down_right,q12).
t(q2,puup,step_left,q3).
t(q2,uppp,step_left,q3).
t(q2,upup,step_left,q3).
t(q2,uupp,step_left,q3).
t(q2,uuup,step_left,q3).
t(q2,pppp,step_up_left,q30).
t(q0,pppp,step_up,q0).
t(q2,pppu,step_up_left,q30).
t(q2,ppup,step_up_left,q30).
t(q2,ppuu,step_up_left,q30).
t(q2,pupp,step_up_left,q30).
t(q2,pupu,step_up_left,q30).
t(q2,puup,step_up_left,q30).
t(q2,puuu,step_up_left,q30).
t(q0,pppp,step_down,q2).
t(q0,pppu,step_down,q2).
t(q0,puup,step_up,q0).
t(q0,pupp,step_down,q2).
t(q0,pupu,step_down,q2).
t(q0,uppp,step_down,q2).
t(q0,uppu,step_down,q2).
t(q0,uupp,step_down,q2).
t(q0,puuu,step_up,q0).
t(q3,pppp,step_up,q0).
t(q3,pppu,step_up,q0).
t(q0,uupu,step_down,q2).
t(q3,ppup,step_up,q0).
t(q3,ppuu,step_up,q0).
t(q3,pupp,step_up,q0).
t(q3,pupu,step_up,q0).
t(q3,puup,step_up,q0).
t(q3,puuu,step_up,q0).
t(q3,pppp,step_up_right,q01).
t(q3,pppu,step_up_right,q01).
t(q3,ppup,step_up_right,q01).
t(q3,ppuu,step_up_right,q01).
t(q3,pupp,step_up_right,q01).
t(q3,pupu,step_up_right,q01).
t(q3,puup,step_up_right,q01).
t(q3,puuu,step_up_right,q01).
t(q3,uppp,step_up_right,q01).
t(q3,uppu,step_up_right,q01).
t(q3,upup,step_up_right,q01).
t(q3,upuu,step_up_right,q01).
t(q3,uupp,step_up_right,q01).
t(q3,uupu,step_up_right,q01).
t(q3,uuup,step_up_right,q01).
t(q3,uuuu,step_up_right,q01).
t(q3,pppp,step_right,q1).
t(q0,pppp,step_down_left,q23).
t(q3,pppu,step_right,q1).
t(q3,ppup,step_right,q1).
t(q3,ppuu,step_right,q1).
t(q3,uppp,step_right,q1).
t(q3,uppu,step_right,q1).
t(q3,upup,step_right,q1).
t(q0,pppu,step_down_left,q23).
t(q3,upuu,step_right,q1).
t(q3,pppp,step_down_right,q12).
t(q3,pppu,step_down_right,q12).
t(q3,pupp,step_down_right,q12).
t(q0,ppup,step_down_left,q23).
t(q3,pupu,step_down_right,q12).
t(q3,uppp,step_down_right,q12).
t(q3,uppu,step_down_right,q12).
t(q3,uupp,step_down_right,q12).
t(q3,uupu,step_down_right,q12).
t(q0,ppuu,step_down_left,q23).
t(q3,pppp,step_down,q2).
t(q3,pppu,step_down,q2).
t(q3,pupp,step_down,q2).
t(q3,pupu,step_down,q2).
t(q3,uppp,step_down,q2).
t(q3,uppu,step_down,q2).
t(q0,pupp,step_down_left,q23).
t(q3,uupp,step_down,q2).
t(q3,uupu,step_down,q2).
t(q3,pppp,step_down_left,q23).
t(q3,pppu,step_down_left,q23).
t(q3,ppup,step_down_left,q23).
t(q3,ppuu,step_down_left,q23).
t(q0,pupu,step_down_left,q23).
t(q3,pupp,step_down_left,q23).
t(q3,pupu,step_down_left,q23).
t(q3,puup,step_down_left,q23).
t(q3,puuu,step_down_left,q23).
t(q3,uppp,step_down_left,q23).
t(q3,uppu,step_down_left,q23).
t(q3,upup,step_down_left,q23).
t(q3,upuu,step_down_left,q23).
t(q3,uupp,step_down_left,q23).
t(q3,uupu,step_down_left,q23).
t(q0,puup,step_down_left,q23).
t(q3,uuup,step_down_left,q23).
t(q3,uuuu,step_down_left,q23).
t(q3,pppp,step_left,q3).
t(q3,ppup,step_left,q3).
t(q3,pupp,step_left,q3).
t(q3,puup,step_left,q3).
t(q0,puuu,step_down_left,q23).
t(q3,uppp,step_left,q3).
t(q3,upup,step_left,q3).
t(q3,uupp,step_left,q3).
t(q3,uuup,step_left,q3).
t(q3,pppp,step_up_left,q30).
t(q0,uppp,step_down_left,q23).
t(q3,pppu,step_up_left,q30).
t(q3,ppup,step_up_left,q30).
t(q3,ppuu,step_up_left,q30).
t(q3,pupp,step_up_left,q30).
t(q3,pupu,step_up_left,q30).
t(q3,puup,step_up_left,q30).
t(q3,puuu,step_up_left,q30).
t(q0,uppu,step_down_left,q23).
t(q0,upup,step_down_left,q23).
t(q0,upuu,step_down_left,q23).
t(q0,uupp,step_down_left,q23).
t(q0,uupu,step_down_left,q23).
t(q0,uuup,step_down_left,q23).
t(q0,uuuu,step_down_left,q23).
t(q0,pppp,step_left,q3).
t(q0,ppup,step_left,q3).
t(q0,pupp,step_left,q3).
t(q0,puup,step_left,q3).
t(q0,uppp,step_left,q3).
t(q0,upup,step_left,q3).
t(q0,uupp,step_left,q3).
t(q0,uuup,step_left,q3).
t(q0,pppp,step_up_left,q30).
t(q0,pppu,step_up_left,q30).
t(q0,ppup,step_up_left,q30).
t(q0,ppuu,step_up_left,q30).
t(q0,pupp,step_up_left,q30).
t(q0,pupu,step_up_left,q30).
t(q0,puup,step_up_left,q30).
t(q0,puuu,step_up_left,q30).
