:-module(coloured_graph, [dataset_path/1
                         ]).

:-use_module(graph_generator_configuration).
:-use_module(graph_generator).

/** <module> Coloured graph experiment file shim.

Interface file to the four datasets generated by
data/coloured_graph/graph_generator.pl.

*/

%!      dataset_path(-Path) is det.
%
%       Report the Path of the current dataset.
%
%       The "current dataset" is the dataset determined by the
%       configuration option mislabelling_type/1. Typically, it should
%       reside in the coloured_graph/output directory. If not, run
%       write_dataset/0 in graph_generator.pl.
%
dataset_path(Path):-
        graph_generator_configuration:mislabelling_type(L)
        ,graph_generator_configuration:target_prefix_arity(T,_A)
        ,graph_generator_configuration:output_root(Root)
        ,atomic_list_concat([T,L],'_',Bn)
        ,file_name_extension(Bn,'.pl',Fn)
        ,directory_file_path(Root,Fn,Path).

% Create the current dataset if it doesn't exist,
% load it and re-export its experiment file interface predicates.
:-dataset_path(P)
  ,(   \+ exists_file(P)
   ->  write_dataset
   ;   true
   )
  ,reexport(P).
